---
- name: Crear VM en Hyper-V usando ISO en NAS (sin copiar ISO) + unattended
  hosts: localhost
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts válidos
    hyperv_hosts:
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXFCFVB
      - SMXHYPVA

    # vSwitch por defecto
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar discos de la VM
    candidate_drives:
      - 'D'
      - 'E'

    # ISO por defecto en NAS (Windows)
    iso_path_default: '\\10.138.120.130\isos\SERVER_EVAL_x64FRE_es-es.iso'

    # Datos de la NAS (para el SMB Global Mapping)
    nas_server: '10.138.120.130'
    nas_share: 'isos'
    nas_user: 'NASUSER_AQUI'
    nas_pass: 'NASPASS_AQUI'

  tasks:

    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - hyperv_host is defined
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
          - vm_cidr is defined        # ej: 10.138.104.55/24
          - vm_gateway is defined
          - vm_dns1 is defined
        fail_msg: >-
          Faltan variables: hyperv_host, vm_name, memory_gb, cpu, disk_gb,
          vm_cidr, vm_gateway, vm_dns1.

    - name: Validar hyperv_host permitido
      ansible.builtin.assert:
        that:
          - hyperv_host in hyperv_hosts
        fail_msg: "El host {{ hyperv_host }} no está en la lista de hyperv_hosts permitidos."

    - name: Normalizar variables
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"
        # Rutas en la NAS para XML y ISO de unattended
        unattended_nas_dir: "\\\\{{ nas_server }}\\{{ nas_share }}\\unattend_{{ vm_name }}"
        unattended_xml_path: "{{ unattended_nas_dir }}\\autounattend.xml"
        unattended_iso_path: "\\\\{{ nas_server }}\\{{ nas_share }}\\{{ vm_name }}_autounattend.iso"

    # -------------------------------------------------------------------
    # 1) Crear SMB Global Mapping para que Hyper-V pueda acceder a la NAS
    # -------------------------------------------------------------------
    - name: Crear SMB Global Mapping hacia la NAS para Hyper-V
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$Server,
            [string]$Share,
            [string]$User,
            [string]$Pass
          )

          $remotePath = "\\$Server\$Share"

          $sec  = ConvertTo-SecureString $Pass -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($User, $sec)

          try {
            # Si ya existe, no truena
            $existing = Get-SmbGlobalMapping -RemotePath $remotePath -ErrorAction SilentlyContinue
            if ($existing) {
              Write-Host "MAPPING-ALREADY: $remotePath"
            } else {
              New-SmbGlobalMapping `
                -RemotePath $remotePath `
                -Credential $cred `
                -Persistent $true `
                -ErrorAction Stop | Out-Null
              Write-Host "MAPPING-OK: $remotePath"
            }
          } catch {
            throw "Error al crear SmbGlobalMapping para $remotePath : $($_.Exception.Message)"
          }
        parameters:
          Server: "{{ nas_server }}"
          Share: "{{ nas_share }}"
          User: "{{ nas_user }}"
          Pass: "{{ nas_pass }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true

    # -------------------------------------------------------------------
    # 2) Preparar carpeta y autounattend.xml en la NAS
    # -------------------------------------------------------------------
    - name: Crear carpeta de unattended en la NAS
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$DirPath
          )
          if (-not (Test-Path $DirPath)) {
            New-Item -ItemType Directory -Path $DirPath | Out-Null
          }
        parameters:
          DirPath: "{{ unattended_nas_dir }}"
      delegate_to: "{{ hyperv_host }}"

    - name: Generar autounattend.xml en la NAS para esta VM
      ansible.builtin.template:
        src: "templates/autounattend.xml.j2"
        dest: "{{ unattended_xml_path }}"
      delegate_to: "{{ hyperv_host }}"

    # -------------------------------------------------------------------
    # 3) Crear ISO de unattended directamente en la NAS
    # -------------------------------------------------------------------
    - name: Crear ISO autounattend en la NAS para esta VM
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$XmlDir,
            [string]$IsoPath
          )

          if (Test-Path $IsoPath) {
            Remove-Item -Path $IsoPath -Force
          }

          try {
            Import-Module PowerShellCookbook -ErrorAction Stop
          } catch {
            throw "No se pudo importar PowerShellCookbook. Asegúrate de tener New-IsoFile disponible en el host Hyper-V."
          }

          New-IsoFile -Source $XmlDir -Destination $IsoPath -Force
          Write-Host "ISO de unattended creado en NAS: $IsoPath"
        parameters:
          XmlDir: "{{ unattended_nas_dir }}"
          IsoPath: "{{ unattended_iso_path }}"
      delegate_to: "{{ hyperv_host }}"

    # -------------------------------------------------------------------
    # 4) Crear VM en Hyper-V usando ISO remota desde la NAS + unattended
    # -------------------------------------------------------------------
    - name: Crear VM en Hyper-V con ISO en NAS + ISO unattended
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,
            [string]$UnattendIsoPath,
            [string[]]$CandidateDrives
          )

          Import-Module Hyper-V

          # 1. Elegir la unidad con más espacio libre (D o E)
          $drives = foreach ($d in $CandidateDrives) {
            try { Get-PSDrive -Name $d -ErrorAction Stop } catch { $null }
          }
          if (-not $drives) {
            throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host."
          }

          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1

          $root        = $bestDrive.Root.TrimEnd('\')      # "D:" o "E:"
          $clusterRoot = Join-Path $root $VmName           # D:\SMXPRE-PRUEBA

          # 2. Carpeta para discos: D:\VMNAME\Virtual Hard Disks
          if (-not (Test-Path $clusterRoot)) {
            New-Item -ItemType Directory -Path $clusterRoot -Force | Out-Null
          }
          $vhdRoot = Join-Path $clusterRoot "Virtual Hard Disks"
          if (-not (Test-Path $vhdRoot)) {
            New-Item -ItemType Directory -Path $vhdRoot -Force | Out-Null
          }

          $VmPath  = $root                              # Path de la VM → raíz del disco
          $VhdPath = Join-Path $vhdRoot "$VmName.vhdx"  # D:\VMNAME\Virtual Hard Disks\VMNAME.vhdx

          Write-Host "Path base Hyper-V       : $VmPath"
          Write-Host "Carpeta discos (vhdRoot): $vhdRoot"
          Write-Host "Disco VHDX              : $VhdPath"

          # 3. Validar ISO Windows (NAS)
          if (-not (Test-Path $IsoPath)) {
            throw "La ISO de Windows no es accesible desde este host: $IsoPath"
          }
          Write-Host "ISO Windows: $IsoPath"

          # 4. Validar ISO unattended (NAS)
          if (-not (Test-Path $UnattendIsoPath)) {
            throw "La ISO de unattended no es accesible desde este host: $UnattendIsoPath"
          }
          Write-Host "ISO unattended (NAS): $UnattendIsoPath"

          # 5. Crear VHDX si no existe
          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
          }

          # 6. Crear VM si no existe
          if (-not (Get-VM -Name $VmName -ErrorAction SilentlyContinue)) {
            New-VM -Name $VmName `
                   -MemoryStartupBytes $MemoryBytes `
                   -Generation 2 `
                   -VHDPath $VhdPath `
                   -SwitchName $SwitchName `
                   -Path $VmPath | Out-Null
          } else {
            Write-Host "La VM $VmName ya existe, no se crea de nuevo."
          }

          # 7. CPU y memoria dinámica
          Set-VMProcessor -VMName $VmName -Count $CpuCount
          Set-VMMemory -VMName $VmName `
            -DynamicMemoryEnabled $true `
            -MinimumBytes 1GB `
            -MaximumBytes ($MemoryBytes * 2)

          # 8. Montar ISO Windows en DVD principal
          $dvdMain = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($dvdMain) {
            Set-VMDvdDrive -VMName $VmName `
              -ControllerNumber $dvdMain.ControllerNumber `
              -ControllerLocation $dvdMain.ControllerLocation `
              -Path $IsoPath
          } else {
            $dvdMain = Add-VMDvdDrive -VMName $VmName -Path $IsoPath
          }

          # 9. Montar ISO unattended como segundo DVD
          $dvdUnattend = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue |
                         Where-Object { $_.Path -eq $UnattendIsoPath }

          if (-not $dvdUnattend) {
            Add-VMDvdDrive -VMName $VmName -Path $UnattendIsoPath | Out-Null
          }

          # 10. Poner el DVD principal como primer dispositivo de arranque
          $dvdBoot = Get-VMDvdDrive -VMName $VmName | Where-Object { $_.Path -eq $IsoPath }
          Set-VMFirmware -VMName $VmName -FirstBootDevice $dvdBoot

          # 11. Iniciar VM
          try {
            Start-VM -Name $VmName -ErrorAction SilentlyContinue
            Write-Host "VM iniciada: $VmName. La instalación desatendida debería comenzar."
          } catch {
            Write-Host "ADVERTENCIA: no se pudo iniciar la VM $VmName : $($_.Exception.Message)"
          }

        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          UnattendIsoPath: "{{ unattended_iso_path }}"
          CandidateDrives: "{{ candidate_drives }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true
