---
- name: Crear VM en Hyper-V (cascarón + disco + ISO desde ruta compartida)
  hosts: localhost
  gather_facts: no

  vars:
    # Hosts válidos donde se permite crear VMs
    hyperv_hosts:
      - SMXFCFVB
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXHYPVA

    # vSwitch por defecto (se puede sobreescribir con v_switch)
    default_switch: 'LAN-Prod'

    # Unidades que pueden contener las VMs (el script elegirá la que tenga más espacio)
    candidate_drives:
      - 'D'
      - 'E'

    # Ruta del ISO por defecto (puedes sobreescribirla con iso_path)
    iso_path_default: '\\10.138.120.15\isos\Rocky-9.6-x86_64-dvd.iso'

  tasks:

    # Validar que vengan todas las variables desde Semaphore
    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - hyperv_host is defined
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
          - hyperv_host | length > 0
          - vm_name | length > 0
        fail_msg: "Faltan variables: hyperv_host, vm_name, memory_gb, cpu, disk_gb (y opcionalmente v_switch, iso_path)."

    - name: Validar que el host elegido está en la lista
      ansible.builtin.assert:
        that:
          - hyperv_host in hyperv_hosts
        fail_msg: "El host {{ hyperv_host }} no está en la lista permitida."

    - name: Normalizar variables y defaults
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"

    - name: Crear VM en Hyper-V (estructura, VHDX y ISO)
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,
            [string[]]$CandidateDrives
          )

          Import-Module Hyper-V

          # 1. Elegir la unidad con más espacio libre (D o E)
          $drives = foreach ($d in $CandidateDrives) {
            try {
              Get-PSDrive -Name $d -ErrorAction Stop
            } catch {
              $null
            }
          }

          if (-not $drives) {
            throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host."
          }

          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1
          Write-Host "Usando unidad $($bestDrive.Name): libre $([math]::Round($bestDrive.Free / 1GB, 2)) GB"

          # 2. Carpeta raíz tipo 'D:\NOMBREHOST'
          $hostFolderName = $Env:COMPUTERNAME
          $root        = $bestDrive.Root           # D:\
          $clusterRoot = Join-Path $root $hostFolderName

          # Subcarpetas estándar
          $snapshotsRoot = Join-Path $clusterRoot "Snapshots"
          $vhdRoot       = Join-Path $clusterRoot "Virtual Hard Disks"
          $vmRoot        = Join-Path $clusterRoot "Virtual Machines"

          foreach ($p in @($clusterRoot, $snapshotsRoot, $vhdRoot, $vmRoot)) {
            if (-not (Test-Path $p)) {
              New-Item -ItemType Directory -Path $p -Force | Out-Null
            }
          }

          # 3. Rutas de esta VM
          $VmPath  = Join-Path $vmRoot $VmName
          $VhdPath = Join-Path $vhdRoot ("{0}.vhdx" -f $VmName)

          Write-Host "Carpeta de la VM : $VmPath"
          Write-Host "Disco de la VM   : $VhdPath"

          if (-not (Test-Path $VmPath)) {
            New-Item -ItemType Directory -Path $VmPath -Force | Out-Null
          }

          # 4. Crear VHDX vacío (disco dinámico)
          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
          }

          # 5. Crear VM si no existe
          if (-not (Get-VM -Name $VmName -ErrorAction SilentlyContinue)) {
            New-VM -Name $VmName `
                   -MemoryStartupBytes $MemoryBytes `
                   -Generation 2 `
                   -VHDPath $VhdPath `
                   -SwitchName $SwitchName `
                   -Path $VmPath | Out-Null
          } else {
            Write-Host "La VM $VmName ya existe, no se vuelve a crear."
          }

          # 6. CPU
          Set-VMProcessor -VMName $VmName -Count $CpuCount

          # 7. Memoria dinámica
          Set-VMMemory -VMName $VmName `
            -DynamicMemoryEnabled $true `
            -MinimumBytes 1GB `
            -MaximumBytes ($MemoryBytes * 2)

          # 8. Montar ISO en la unidad de DVD
          $dvd = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue
          if ($dvd) {
            Set-VMDvdDrive -VMName $VmName -ControllerNumber $dvd.ControllerNumber -ControllerLocation $dvd.ControllerLocation -Path $IsoPath
          } else {
            Add-VMDvdDrive -VMName $VmName -Path $IsoPath | Out-Null
          }

          # 9. Poner el DVD como primer dispositivo de arranque
          $dvd = Get-VMDvdDrive -VMName $VmName
          Set-VMFirmware -VMName $VmName -FirstBootDevice $dvd

          # 10. Iniciar VM
          Start-VM -Name $VmName

        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          CandidateDrives: "{{ candidate_drives }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true
