---
- name: Crear VM en Hyper-V (cascarón + disco + ISO desde ruta compartida)
  hosts: localhost
  gather_facts: no

  vars:
    # Hosts válidos
    hyperv_hosts:
      - SMXFCFVB
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXHYPVA

    # vSwitch por defecto
    default_switch: 'LAN-Prod'

    # Unidades donde pueden vivir las VMs
    candidate_drives:
      - 'D'
      - 'E'

    # Ruta del ISO (UNC) accesible desde los HYPER-V
    iso_path: '\\10.138.120.15\isos\Rocky-9.6-x86_64-dvd.iso'

  vars_prompt:
    - name: hyperv_host
      prompt: "¿En qué host Hyper-V quieres crear la VM? (ej. SMXHVCEDIS)"
      private: no

    - name: vm_name
      prompt: "Nombre de la VM"
      private: no

    - name: memory_gb
      prompt: "Memoria en GB (ej. 8)"
      private: no
      default: "8"

    - name: cpu
      prompt: "Número de vCPU (ej. 4)"
      private: no
      default: "4"

    - name: disk_gb
      prompt: "Tamaño del disco en GB (ej. 100)"
      private: no
      default: "100"

    - name: v_switch
      prompt: "Nombre del vSwitch (ENTER para usar {{ default_switch }})"
      private: no
      default: "{{ default_switch }}"

  collections:
    - ansible.windows

  tasks:

    - name: Validar que el host elegido está en la lista
      ansible.builtin.assert:
        that:
          - hyperv_host in hyperv_hosts
        fail_msg: "El host {{ hyperv_host }} no está en la lista permitida."

    - name: Calcular memoria y disco
      ansible.builtin.set_fact:
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"

    - name: Crear VM en el host seleccionado usando PowerShell (estructura, VHDX, ISO)
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,
            [string[]]$CandidateDrives
          )

          Import-Module Hyper-V

          # 1. Elegir la unidad con más espacio libre (D o E)
          $drives = foreach ($d in $CandidateDrives) {
            try {
              Get-PSDrive -Name $d -ErrorAction Stop
            } catch {
              $null
            }
          }

          if (-not $drives) {
            throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host."
          }

          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1
          Write-Host "Usando unidad $($bestDrive.Name): libre $([math]::Round($bestDrive.Free / 1GB, 2)) GB"

          # 2. Carpeta raíz tipo 'D:\NOMBREHOST'
          $hostFolderName = $Env:COMPUTERNAME
          $root        = $bestDrive.Root           # D:\
          $clusterRoot = Join-Path $root $hostFolderName

          # Subcarpetas estándar
          $snapshotsRoot = Join-Path $clusterRoot "Snapshots"
          $vhdRoot       = Join-Path $clusterRoot "Virtual Hard Disks"
          $vmRoot        = Join-Path $clusterRoot "Virtual Machines"

          foreach ($p in @($clusterRoot, $snapshotsRoot, $vhdRoot, $vmRoot)) {
            if (-not (Test-Path $p)) {
              New-Item -ItemType Directory -Path $p -Force | Out-Null
            }
          }

          # 3. Rutas de esta VM
          $VmPath  = Join-Path $vmRoot $VmName
          $VhdPath = Join-Path $vhdRoot ("{0}.vhdx" -f $VmName)

          Write-Host "Carpeta de la VM : $VmPath"
          Write-Host "Disco de la VM   : $VhdPath"

          if (-not (Test-Path $VmPath)) {
            New-Item -ItemType Directory -Path $VmPath -Force | Out-Null
          }

          # 4. Crear VHDX vacío (disco dinámico)
          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
          }

          # 5. Crear VM si no existe
          if (-not (Get-VM -Name $VmName -ErrorAction SilentlyContinue)) {
            New-VM -Name $VmName `
                   -MemoryStartupBytes $MemoryBytes `
                   -Generation 2 `
                   -VHDPath $VhdPath `
                   -SwitchName $SwitchName `
                   -Path $VmPath | Out-Null
          } else {
            Write-Host "La VM $VmName ya existe, no se vuelve a crear."
          }

          # 6. CPU
          Set-VMProcessor -VMName $VmName -Count $CpuCount

          # 7. Memoria dinámica
          Set-VMMemory -VMName $VmName `
            -DynamicMemoryEnabled $true `
            -MinimumBytes 1GB `
            -MaximumBytes ($MemoryBytes * 2)

          # 8. Montar ISO en la unidad de DVD
          $dvd = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue
          if ($dvd) {
            Set-VMDvdDrive -VMName $VmName -ControllerNumber $dvd.ControllerNumber -ControllerLocation $dvd.ControllerLocation -Path $IsoPath
          } else {
            Add-VMDvdDrive -VMName $VmName -Path $IsoPath | Out-Null
          }

          # 9. Poner el DVD como primer dispositivo de arranque
          $dvd = Get-VMDvdDrive -VMName $VmName
          Set-VMFirmware -VMName $VmName -FirstBootDevice $dvd

          # 10. Iniciar VM
          Start-VM -Name $VmName

        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu | int }}"
          SwitchName: "{{ v_switch }}"
          IsoPath: "{{ iso_path }}"
          CandidateDrives: "{{ candidate_drives }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true
