---
- name: Crear VM en Hyper-V (cascarón + disco + ISO desde NAS con autenticación)
  hosts: localhost
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts válidos donde se permite crear VMs
    hyperv_hosts:
      - SMXFCFVB
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXHYPVA

    # vSwitch por defecto si no se manda v_switch
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar las VMs
    candidate_drives:
      - 'D'
      - 'E'

    # ISO por defecto (puedes cambiarla o dejar que siempre llegue por variable)
    iso_path_default: '\\10.138.120.130\isos\SERVER_EVAL_x64FRE_es-es.iso'

    # Drive temporal a usar para mapear el recurso compartido (debe ser una letra libre)
    iso_drive_letter: 'Z'


  tasks:

    # ... [Validaciones anteriores omitidas por brevedad] ...

    - name: Crear VM en Hyper-V (estructura, VHDX y ISO)
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,
            [string]$IsoUser,
            [string]$IsoPassword,
            [string]$IsoDriveLetter,
            [string[]]$CandidateDrives
          )

          Import-Module Hyper-V

          # Usamos un bloque try/finally para garantizar que la unidad mapeada se limpie
          try {

              # =================================================================
              # 1. AUTENTICACIÓN Y MONTAJE TEMPORAL DE ISO
              # =================================================================
              $OriginalIsoPath = $IsoPath
              $effectiveCheckPath = $IsoPath
              $isoOk = $false
              $authSuccessful = $false

              if ($IsoPath -and $IsoUser -and $IsoPassword) {
                  Write-Host "Intentando autenticar y mapear el recurso compartido de la ISO..."

                  # Crear objeto de credenciales
                  $secPass = ConvertTo-SecureString -String $IsoPassword -AsPlainText -Force
                  $credential = New-Object System.Management.Automation.PSCredential($IsoUser, $secPass)

                  # Separar la ruta UNC del nombre del archivo
                  $isoFileName = Split-Path -Path $IsoPath -Leaf
                  $isoUncRoot = Split-Path -Path $IsoPath -Parent # Ej: \\10.138.120.130\isos

                  try {
                      # Limpiar unidad previa si existe (silenciosamente)
                      Remove-PSDrive -Name $IsoDriveLetter -Force -ErrorAction SilentlyContinue | Out-Null
                      
                      # Crear una unidad de red temporal (ej: Z:) con credenciales.
                      # ESTO INYECTA LAS CREDENCIALES EN LA SESIÓN.
                      New-PSDrive -Name $IsoDriveLetter -PSProvider FileSystem -Root $isoUncRoot -Credential $credential -Persist:$false -ErrorAction Stop | Out-Null
                      
                      $authSuccessful = $true
                      $effectiveCheckPath = Join-Path "$($IsoDriveLetter):" $isoFileName
                      Write-Host "Autenticación exitosa. Check Path: $effectiveCheckPath"

                      # Prueba de acceso de archivo con la unidad mapeada (Test-Path)
                      $isoOk = Test-Path $effectiveCheckPath -ErrorAction Stop

                      if ($isoOk) {
                          Write-Host "VERIFICACIÓN OK: ISO accesible a través de la unidad temporal."
                      } else {
                          Write-Host "ERROR: Autenticación OK, pero el archivo no se encuentra en la ruta: $effectiveCheckPath"
                      }

                  } catch {
                      Write-Host "ERROR CRÍTICO DE AUTENTICACIÓN/ACCESO. La ISO NO será montada."
                      Write-Host ("Detalle: {0}" -f $_.Exception.Message)
                      $isoOk = $false # Forzar que no se intente montar la ISO
                      $OriginalIsoPath = $null
                  }
              }

              # =================================================================
              # 2. SELECCIÓN DE UNIDAD Y CREACIÓN DE CARPETAS (El código es idéntico al anterior)
              # =================================================================
              # ... [Contenido de la Sección 2. SELECCIÓN DE UNIDAD Y CREACIÓN DE CARPETAS] ...

              # Elegir la unidad con más espacio libre (D o E)
              $drives = foreach ($d in $CandidateDrives) {
                try { Get-PSDrive -Name $d -ErrorAction Stop } catch { $null }
              }

              if (-not $drives) { throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host." }

              $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1
              Write-Host "Usando unidad $($bestDrive.Name): libre $([math]::Round($bestDrive.Free / 1GB, 2)) GB"

              # Estructura de carpetas
              $root      = $bestDrive.Root
              $clusterRoot = Join-Path $root $VmName
              $vhdRoot       = Join-Path $clusterRoot "Virtual Hard Disks"
              $VmPath = $clusterRoot
              $VhdPath = Join-Path $vhdRoot ("{0}.vhdx" -f $VmName) 

              foreach ($p in @($clusterRoot, $vhdRoot)) {
                if (-not (Test-Path $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null }
              }
              
              # =================================================================
              # 3. CREACIÓN Y CONFIGURACIÓN DE LA VM (El código es idéntico al anterior)
              # =================================================================

              # Crear VHDX vacío
              if (-not (Test-Path $VhdPath)) { New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null }

              # Crear VM si no existe (comando en una sola línea)
              if (-not (Get-VM -Name $VmName -ErrorAction SilentlyContinue)) {
                New-VM -Name $VmName -MemoryStartupBytes $MemoryBytes -Generation 2 -VHDPath $VhdPath -SwitchName $SwitchName -Path $VmPath | Out-Null
              } else {
                Write-Host "La VM $VmName ya existe, no se vuelve a crear."
              }

              # Configurar VM
              Set-VMProcessor -VMName $VmName -Count $CpuCount
              Set-VMMemory -VMName $VmName -DynamicMemoryEnabled $true -MinimumBytes 1GB -MaximumBytes ($MemoryBytes * 2) # Memoria dinámica en una sola línea
              
              # Montar ISO (usando la ruta UNC original, NO el drive mapeado)
              if ($isoOk -and $OriginalIsoPath) {
                try {
                  Write-Host "Montando ISO usando ruta UNC original ($OriginalIsoPath)."
                  
                  $dvd = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue
                  if ($dvd) {
                    Set-VMDvdDrive -VMName $VmName -ControllerNumber $dvd.ControllerNumber -ControllerLocation $dvd.ControllerLocation -Path $OriginalIsoPath -ErrorAction Stop
                  } else {
                    Add-VMDvdDrive -VMName $VmName -Path $OriginalIsoPath -ErrorAction Stop | Out-Null
                  }

                  $dvd = Get-VMDvdDrive -VMName $VmName
                  Set-VMFirmware -VMName $VmName -FirstBootDevice $dvd
                  Write-Host "ISO montada exitosamente y puesta como primer dispositivo de arranque."
                } catch {
                  Write-Host ("ADVERTENCIA: Error al montar la ISO en la VM {0}: {1}" -f $VmName, $_.Exception.Message)
                }
              } else {
                  Write-Host "Skipping ISO mount because authentication or file check failed earlier."
              }
              
              # Iniciar VM
              Start-VM -Name $VmName

          } finally {
              # =================================================================
              # 4. LIMPIEZA
              # =================================================================
              # Si la unidad mapeada existe, la eliminamos.
              if ($IsoDriveLetter -and (Get-PSDrive -Name $IsoDriveLetter -ErrorAction SilentlyContinue)) {
                  Write-Host "Limpiando unidad mapeada temporal ($($IsoDriveLetter):)."
                  Remove-PSDrive -Name $IsoDriveLetter -Force -ErrorAction SilentlyContinue | Out-Null
                  Write-Host "Limpieza completada."
              }
          }


        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          CandidateDrives: "{{ candidate_drives }}"
          # Credenciales
          IsoUser: "{{ iso_user }}"
          IsoPassword: "{{ iso_password }}"
          IsoDriveLetter: "{{ iso_drive_letter }}"
        delegate_to: "{{ hyperv_host }}"
        run_once: true
