---
- name: Crear VM en Hyper-V (cascarón + disco + ISO desde ruta compartida)
  hosts: localhost
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts válidos donde se permite crear VMs
    hyperv_hosts:
      - SMXFCFVB
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXHYPVA

    # vSwitch por defecto si no se manda v_switch
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar las VMs
    candidate_drives:
      - 'D'
      - 'E'

    # ISO por defecto (puedes cambiarla o dejar que siempre llegue por variable)
    iso_path_default: '\\10.138.120.130\isos\SERVER_EVAL_x64FRE_es-es.iso'

  tasks:

    # -----------------------------------------------------------------------
    # Validaciones de variables que vienen desde Semaphore
    # -----------------------------------------------------------------------
    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - hyperv_host is defined
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
          - hyperv_host | length > 0
          - vm_name | length > 0
        fail_msg: "Faltan variables: hyperv_host, vm_name, memory_gb, cpu, disk_gb."

    - name: Validar que el host elegido está en la lista permitida
      ansible.builtin.assert:
        that:
          - hyperv_host in hyperv_hosts
        fail_msg: "El host {{ hyperv_host }} no está en la lista de hyperv_hosts permitidos."

    - name: Normalizar variables y defaults
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"

    - name: Debug de variables (puedes comentar esta tarea si ya no la necesitas)
      ansible.builtin.debug:
        msg:
          hyperv_host: "{{ hyperv_host }}"
          vm_name: "{{ vm_name }}"
          memory_gb: "{{ memory_gb }}"
          cpu: "{{ cpu }}"
          disk_gb: "{{ disk_gb }}"
          v_switch: "{{ v_switch_eff }}"
          iso_path: "{{ iso_path_eff }}"
          iso_user: "{{ iso_user | default('') }}"

    # -----------------------------------------------------------------------
    # Creación de VM en el host Hyper-V seleccionado
    # -----------------------------------------------------------------------
    - name: Crear VM en Hyper-V (estructura, VHDX y ISO)
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,         # \\servidor\share\archivo.iso
            [string]$IsoUser,         # usuario del share (opcional)
            [string]$IsoPassword,     # contraseña (opcional)
            [string[]]$CandidateDrives
          )

          Import-Module Hyper-V

          # 1. Elegir la unidad con más espacio libre (D o E)
          $drives = foreach ($d in $CandidateDrives) {
            try { Get-PSDrive -Name $d -ErrorAction Stop } catch { $null }
          }

          if (-not $drives) {
            throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host."
          }

          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1
          Write-Host "Usando unidad $($bestDrive.Name): libre $([math]::Round($bestDrive.Free / 1GB, 2)) GB"

          # 2. Carpeta raíz tipo 'D:\NOMBRE-VM'
          $root        = $bestDrive.Root             # D:\ o E:\
          $clusterRoot = Join-Path $root $VmName     # D:\SMXPRE-PRUEBA

          # Subcarpetas estándar dentro de D:\NOMBRE-VM\
          $snapshotsRoot = Join-Path $clusterRoot "Snapshots"           # D:\NOMBRE-VM\Snapshots
          $vhdRoot       = Join-Path $clusterRoot "Virtual Hard Disks"  # D:\NOMBRE-VM\Virtual Hard Disks
          $vmRoot        = Join-Path $clusterRoot "Virtual Machines"    # D:\SMXPRE-PRUEBA\Virtual Machines

          foreach ($p in @($clusterRoot, $snapshotsRoot, $vhdRoot, $vmRoot)) {
            if (-not (Test-Path $p)) {
              New-Item -ItemType Directory -Path $p -Force | Out-Null
            }
          }

          # 3. Rutas finales                                  
          $VhdPath = Join-Path $vhdRoot ("{0}.vhdx" -f $VmName)     # D:\NOMBRE-VM\Virtual Hard Disks\NOMBRE-VM.vhdx

          Write-Host "Carpeta base de la VM : $VmPath"
          Write-Host "Disco de la VM        : $VhdPath"

          # 4. Preparar ruta efectiva de ISO (con o sin credenciales)
          $effectiveIsoPath = $IsoPath

          if ($IsoPath -and $IsoPath.Trim() -ne '' -and $IsoUser -and $IsoPassword) {

            $shareRoot = Split-Path $IsoPath -Parent   # \\servidor\isos
            $fileName  = Split-Path $IsoPath -Leaf     # archivo.iso

            Write-Host "Creando sesión SMB a $shareRoot con el usuario $IsoUser"

            try {
              # Convertir password
              $sec  = ConvertTo-SecureString $IsoPassword -AsPlainText -Force

              # Limpiar mapeo previo X:
              try {
                Remove-SmbMapping -LocalPath "X:" -Force -ErrorAction SilentlyContinue | Out-Null
              } catch { }

              New-SmbMapping -LocalPath "X:" -RemotePath $shareRoot -UserName $IsoUser -Password $IsoPassword -Persistent:$false -ErrorAction Stop | Out-Null

              $effectiveIsoPath = "X:\$fileName"
              Write-Host "ISO efectiva (mapeada): $effectiveIsoPath"
            } catch {
              throw "No se pudo establecer la sesión SMB para la ISO ($IsoPath) con las credenciales proporcionadas: $($_.Exception.Message)"
            }
          } else {
            Write-Host "Usando ruta de ISO sin credenciales adicionales: $IsoPath"
          }

          # 5. Crear VHDX vacío (dinámico)
          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
          }

          # 6. Crear VM si no existe
          if (-not (Get-VM -Name $VmName -ErrorAction SilentlyContinue)) {
            New-VM -Name $VmName `
                   -MemoryStartupBytes $MemoryBytes `
                   -Generation 2 `
                   -VHDPath $VhdPath `
                   -SwitchName $SwitchName `
                   -Path $VmPath | Out-Null
          } else {
            Write-Host "La VM $VmName ya existe, no se vuelve a crear."
          }

          # 7. Configurar CPU
          Set-VMProcessor -VMName $VmName -Count $CpuCount

          # 8. Memoria dinámica
          Set-VMMemory -VMName $VmName `
            -DynamicMemoryEnabled $true `
            -MinimumBytes 1GB `
            -MaximumBytes ($MemoryBytes * 2)

          # 9. Montar ISO en la unidad de DVD (si tenemos ruta efectiva)
          if ($effectiveIsoPath -and $effectiveIsoPath.Trim() -ne '') {
            $dvd = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue
            if ($dvd) {
              Set-VMDvdDrive -VMName $VmName `
                -ControllerNumber $dvd.ControllerNumber `
                -ControllerLocation $dvd.ControllerLocation `
                -Path $effectiveIsoPath
            } else {
              Add-VMDvdDrive -VMName $VmName -Path $effectiveIsoPath | Out-Null
            }

            # 10. Poner el DVD como primer dispositivo de arranque
            $dvd = Get-VMDvdDrive -VMName $VmName
            Set-VMFirmware -VMName $VmName -FirstBootDevice $dvd
          } else {
            Write-Host "ADVERTENCIA: No se montó ISO porque no se obtuvo una ruta efectiva."
          }

          # 11. Iniciar VM
          Start-VM -Name $VmName

        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          IsoUser: "{{ iso_user | default('') }}"
          IsoPassword: "{{ iso_password | default('') }}"
          CandidateDrives: "{{ candidate_drives }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true
