---
- name: Crear VM en Hyper-V usando ISO en NAS + unattended
  hosts: "{{ hyperv_host }}"
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts válidos
    hyperv_hosts:
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXFCHVB
      - SMXHYPVA

    # Contraseña de Administrador (se puede sobreescribir por extra_vars)
    admin_password: "Passw0rd."

    # vSwitch por defecto
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar discos de la VM
    candidate_drives:
      - 'D'
      - 'E'

    # ISO por defecto en NAS (Windows 2022 eval)
    iso_path_default: '\\10.138.120.130\isos\SERVER_EVAL_x64FRE_es-es.iso'

    # NAS para el SMB Global Mapping
    nas_server: '10.138.120.130'
    nas_share: 'isos'
    nas_user: 'NASUSER_AQUI'
    nas_pass: 'NASPASS_AQUI'

    # Ruta local de oscdimg
    oscdimg_path: 'C:\\Oscdimg\\oscdimg.exe'

  tasks:

    # -------------------------------------------------------------------
    # 0) Validaciones y normalización
    # -------------------------------------------------------------------
    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - hyperv_host is defined
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
          - vm_ip is defined
          - vm_mask is defined
          - vm_gateway is defined
          - vm_dns1 is defined
          - vm_image_index is defined
          - admin_password is defined
        fail_msg: >-
          Faltan variables: hyperv_host, vm_name, memory_gb, cpu, disk_gb,
          vm_ip, vm_mask, vm_gateway, vm_dns1, vm_image_index, admin_password.

    - name: Validar hyperv_host permitido
      ansible.builtin.assert:
        that:
          - hyperv_host in hyperv_hosts
        fail_msg: "El host {{ hyperv_host }} no está en la lista de hyperv_hosts permitidos."

    - name: Normalizar variables numéricas y rutas
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"
        vm_dns2_eff: "{{ vm_dns2 | default(vm_dns1) }}"

        unattended_xml_dir: "C:\\autounattend\\{{ vm_name }}"
        unattended_xml_path: "C:\\autounattend\\{{ vm_name }}\\autounattend.xml"
        unattended_iso_path: "C:\\ISOs\\{{ vm_name }}_autounattend.iso"

    # -------------------------------------------------------------------
    # 1) SMB Global Mapping hacia la NAS
    # -------------------------------------------------------------------
    - name: Crear SMB Global Mapping hacia la NAS para Hyper-V
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$Server,
            [string]$Share,
            [string]$User,
            [string]$Pass
          )

          $remotePath = "\\$Server\$Share"

          $sec  = ConvertTo-SecureString $Pass -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($User, $sec)

          try {
            $existing = Get-SmbGlobalMapping -RemotePath $remotePath -ErrorAction SilentlyContinue
            if ($existing) {
              Write-Host "MAPPING-ALREADY: $remotePath"
            } else {
              try { net use $remotePath /delete /y | Out-Null } catch { }

              New-SmbGlobalMapping `
                -RemotePath $remotePath `
                -Credential $cred `
                -Persistent $true `
                -ErrorAction Stop | Out-Null

              Write-Host "MAPPING-OK: $remotePath"
            }
          } catch {
            throw "Error al crear SmbGlobalMapping para $remotePath : $($_.Exception.Message)"
          }
        parameters:
          Server: "{{ nas_server }}"
          Share: "{{ nas_share }}"
          User: "{{ nas_user }}"
          Pass: "{{ nas_pass }}"

    # -------------------------------------------------------------------
    # 2) Carpetas y autounattend.xml
    # -------------------------------------------------------------------
    - name: Crear carpeta local para autounattend.xml
      ansible.windows.win_file:
        path: "{{ unattended_xml_dir }}"
        state: directory

    - name: Crear carpeta local para ISOs de unattended
      ansible.windows.win_file:
        path: "C:\\ISOs"
        state: directory

    - name: Generar autounattend.xml en el host Hyper-V para esta VM
      ansible.builtin.template:
        src: "templates/autounattend.xml.j2"
        dest: "{{ unattended_xml_path }}"

    # -------------------------------------------------------------------
    # 3) Crear ISO de unattended local con oscdimg
    # -------------------------------------------------------------------
    - name: Crear ISO autounattend local en el host Hyper-V con oscdimg
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$SourcePath,
            [string]$IsoPath,
            [string]$OscdimgPath
          )

          if (-not (Test-Path $SourcePath)) {
            throw "La carpeta origen no existe: $SourcePath"
          }

          if (-not (Test-Path $OscdimgPath)) {
            throw "No se encontró oscdimg.exe en: $OscdimgPath"
          }

          if (Test-Path $IsoPath) {
            Remove-Item -Path $IsoPath -Force
          }

          $args = @('-n','-m','-d', $SourcePath, $IsoPath)

          Write-Host "Ejecutando: $OscdimgPath $($args -join ' ')"

          $p = Start-Process -FilePath $OscdimgPath -ArgumentList $args -Wait -PassThru -NoNewWindow

          if ($p.ExitCode -ne 0) {
            throw "oscdimg terminó con código $($p.ExitCode)."
          }

          Write-Host "ISO de unattended creado localmente: $IsoPath"
        parameters:
          SourcePath: "{{ unattended_xml_dir }}"
          IsoPath: "{{ unattended_iso_path }}"
          OscdimgPath: "{{ oscdimg_path }}"

    # -------------------------------------------------------------------
    # 4) Crear / ajustar VM, VHD, DVDs y firmware
    # -------------------------------------------------------------------
    - name: Crear VM en Hyper-V con ISO en NAS + ISO unattended
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,
            [string]$UnattendIsoPath,
            [string[]]$CandidateDrives,
            [int]$VlanId = 0
          )

          Import-Module Hyper-V

          # 1. Elegir unidad con más espacio (D/E)
          $drives = foreach ($d in $CandidateDrives) {
            try { Get-PSDrive -Name $d -ErrorAction Stop } catch { $null }
          }
          if (-not $drives) {
            throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host."
          }
          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1
          Write-Host "Usando unidad $($bestDrive.Name): $([math]::Round($bestDrive.Free/1GB,2)) GB libres"

          $root          = $bestDrive.Root
          $clusterRoot   = "$root\$VmName"
          $snapshotsRoot = Join-Path $clusterRoot "Snapshots"
          $vhdRoot       = Join-Path $clusterRoot "Virtual Hard Disks"

          foreach ($p in @($clusterRoot, $snapshotsRoot, $vhdRoot)) {
            if (-not (Test-Path $p)) {
              New-Item -ItemType Directory -Path $p -Force | Out-Null
            }
          }

          $VmPath  = $root
          $VhdPath = Join-Path $vhdRoot "$VmName.vhdx"

          # 2. Validar ISOs
          if (-not (Test-Path $IsoPath))          { throw "No se puede acceder a la ISO de Windows: $IsoPath" }
          if (-not (Test-Path $UnattendIsoPath))  { throw "No se puede acceder a la ISO unattended: $UnattendIsoPath" }

          # 3. Crear VHDX si no existe
          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
            Write-Host "VHD creado: $VhdPath"
          } else {
            Write-Host "VHD ya existía: $VhdPath"
          }

          # 4. Crear VM SIN VHD (NoVHD) para controlar puertos
          $vm = Get-VM -Name $VmName -ErrorAction SilentlyContinue
          if (-not $vm) {
            New-VM -Name $VmName `
                   -MemoryStartupBytes $MemoryBytes `
                   -Generation 2 `
                   -SwitchName $SwitchName `
                   -Path $VmPath `
                   -NoVHD | Out-Null
            $vm = Get-VM -Name $VmName
            Write-Host "VM creada: $VmName"
          } else {
            Write-Host "VM ya existía: $VmName"
          }

          # 4.1 VLAN condicional: esperar a que exista el adaptador y aplicar
          if ($VlanId -gt 0) {
            Write-Host "Se solicitó VLAN $VlanId. Buscando adaptador de red de la VM $VmName..."

            $nic = $null
            for ($i = 1; $i -le 10; $i++) {
              $nic = Get-VMNetworkAdapter -VMName $VmName -ErrorAction SilentlyContinue
              if ($nic) { break }
              Start-Sleep -Seconds 1
            }

            if (-not $nic) {
              throw "No se encontró adaptador de red en la VM $VmName después de esperar."
            }

            Write-Host "Adaptador encontrado: $($nic.Name). Aplicando VLAN $VlanId."
            Set-VMNetworkAdapterVlan `
              -VMName $VmName `
              -VMNetworkAdapterName $nic.Name `
              -Access `
              -VlanId $VlanId `
              -ErrorAction Stop

            Write-Host "VLAN $VlanId aplicada correctamente."
          } else {
            Write-Host "No se envió vm_vlan, dejando la VM sin VLAN (untagged)."
            Set-VMNetworkAdapterVlan -VMName $VmName -Untagged -ErrorAction SilentlyContinue
          }

          # 5. Asegurar VHD en SCSI 0:2
          $osDisk = Get-VMHardDiskDrive -VMName $VmName -ErrorAction SilentlyContinue |
                    Where-Object { $_.Path -eq $VhdPath }

          if ($osDisk) {
            if ($osDisk.ControllerNumber -ne 0 -or $osDisk.ControllerLocation -ne 2) {
              Remove-VMHardDiskDrive -VMName $VmName `
                                     -ControllerNumber $osDisk.ControllerNumber `
                                     -ControllerLocation $osDisk.ControllerLocation
              Add-VMHardDiskDrive -VMName $VmName `
                                   -ControllerNumber 0 `
                                   -ControllerLocation 2 `
                                   -Path $VhdPath | Out-Null
            }
          } else {
            Add-VMHardDiskDrive -VMName $VmName `
                                 -ControllerNumber 0 `
                                 -ControllerLocation 2 `
                                 -Path $VhdPath | Out-Null
          }

          # 6. CPU y memoria dinámica
          Set-VMProcessor -VMName $VmName -Count $CpuCount
          Set-VMMemory -VMName $VmName `
            -DynamicMemoryEnabled $true `
            -MinimumBytes 1GB `
            -MaximumBytes ($MemoryBytes * 2)

          # 7. Apagar VM antes de tocar firmware/DVD
          $vm = Get-VM -Name $VmName
          if ($vm.State -ne 'Off') {
            Stop-VM -Name $VmName -TurnOff -Force
            do {
              Start-Sleep -Seconds 1
              $vm = Get-VM -Name $VmName
            } while ($vm.State -ne 'Off')
          }

          # 8. Quitar todos los DVD drives
          Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue |
            ForEach-Object {
              Remove-VMDvdDrive -VMName $VmName `
                                -ControllerNumber $_.ControllerNumber `
                                -ControllerLocation $_.ControllerLocation `
                                -Confirm:$false
            }

          # 9. Agregar DVD de Windows en SCSI 0:0 y unattended en 0:1
          $dvdMain = Add-VMDvdDrive -VMName $VmName `
                                    -ControllerNumber 0 `
                                    -ControllerLocation 0 `
                                    -Path $IsoPath
          $dvdUnattend = Add-VMDvdDrive -VMName $VmName `
                                        -ControllerNumber 0 `
                                        -ControllerLocation 1 `
                                        -Path $UnattendIsoPath

          # 10. Forzar arranque UEFI desde la ISO SIN pedir "Press any key" a nivel firmware
          $dvd = Get-VMDvdDrive -VMName $VmName | Where-Object { $_.Path -eq $IsoPath }

          Set-VMFirmware -VMName $VmName `
            -EnableSecureBoot On `
            -FirstBootDevice $dvd

          Write-Host "Boot UEFI forzado desde DVD principal."

          # 11. Iniciar VM
          $vm = Get-VM -Name $VmName
          if ($vm.State -ne 'Running') {
            Start-VM -Name $VmName | Out-Null
            Write-Host "VM iniciada: $VmName"
          } else {
            Write-Host "VM ya estaba corriendo."
          }

        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          UnattendIsoPath: "{{ unattended_iso_path }}"
          CandidateDrives: "{{ candidate_drives }}"
          VlanId: "{{ vm_vlan | default('0') | int }}"
