---
- name: Crear VM en Hyper-V usando ISO en NAS (sin copiar ISO)
  hosts: localhost
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts válidos
    hyperv_hosts:
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXFCFVB
      - SMXHYPVA

    # vSwitch por defecto
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar discos de la VM
    candidate_drives:
      - 'D'
      - 'E'

    # ISO por defecto en NAS
    iso_path_default: '\\10.138.120.130\isos\SERVER_EVAL_x64FRE_es-es.iso'

    # Datos de la NAS (para el SMB Global Mapping)
    nas_server: '10.138.120.130'
    nas_share: 'isos'
    nas_user: 'NASUSER_AQUI'   # se usará si NO mandas iso_user
    nas_pass: 'NASPASS_AQUI'   # se usará si NO mandas iso_password

  tasks:

    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - hyperv_host is defined
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
        fail_msg: "Faltan variables: hyperv_host, vm_name, memory_gb, cpu, disk_gb."

    - name: Validar hyperv_host permitido
      ansible.builtin.assert:
        that:
          - hyperv_host in hyperv_hosts
        fail_msg: "El host {{ hyperv_host }} no está en la lista de hyperv_hosts permitidos."

    - name: Normalizar variables
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"

    # -------------------------------------------------------------------
    # 1) Crear SMB Global Mapping para que Hyper-V pueda acceder a la NAS
    # -------------------------------------------------------------------
    - name: Crear SMB Global Mapping hacia la NAS para Hyper-V
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$Server,
            [string]$Share,
            [string]$User,
            [string]$Pass
          )

          $remotePath = "\\$Server\$Share"

          $sec  = ConvertTo-SecureString $Pass -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($User, $sec)

          try {
            # Si ya existe, no truena
            $existing = Get-SmbGlobalMapping -RemotePath $remotePath -ErrorAction SilentlyContinue
            if ($existing) {
              Write-Host "MAPPING-ALREADY: $remotePath"
            } else {
              New-SmbGlobalMapping `
                -RemotePath $remotePath `
                -Credential $cred `
                -Persistent $true `
                -ErrorAction Stop | Out-Null
              Write-Host "MAPPING-OK: $remotePath"
            }
          } catch {
            throw "Error al crear SmbGlobalMapping para $remotePath : $($_.Exception.Message)"
          }
        parameters:
          Server: "{{ nas_server }}"
          Share: "{{ nas_share }}"
          # 👇 aquí el cambio importante: usa iso_user/iso_password si vienen en extra_vars
          User: "{{ iso_user | default(nas_user) }}"
          Pass: "{{ iso_password | default(nas_pass) }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true

    # -------------------------------------------------------------------
    # 2) Crear VM en Hyper-V usando ISO remota desde la NAS
    # -------------------------------------------------------------------
    - name: Crear VM en Hyper-V con ISO en NAS
      ansible.windows.win_powershell:
        script: |
          param(
            [string]$VmName,
            [Int64]$MemoryBytes,
            [Int64]$DiskBytes,
            [int]$CpuCount,
            [string]$SwitchName,
            [string]$IsoPath,
            [string[]]$CandidateDrives
          )

          Import-Module Hyper-V

          # 1. Elegir la unidad con más espacio libre (D o E)
          $drives = foreach ($d in $CandidateDrives) {
            try { Get-PSDrive -Name $d -ErrorAction Stop } catch { $null }
          }
          if (-not $drives) {
            throw "Ninguna de las unidades candidatas ($($CandidateDrives -join ', ')) existe en este host."
          }

          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1

          $root        = $bestDrive.Root.TrimEnd('\')      # "D:" o "E:"
          $clusterRoot = Join-Path $root $VmName           # D:\SMXPRE-PRUEBA

          # 2. Carpeta para discos: D:\VMNAME\Virtual Hard Disks
          if (-not (Test-Path $clusterRoot)) {
            New-Item -ItemType Directory -Path $clusterRoot -Force | Out-Null
          }
          $vhdRoot = Join-Path $clusterRoot "Virtual Hard Disks"
          if (-not (Test-Path $vhdRoot)) {
            New-Item -ItemType Directory -Path $vhdRoot -Force | Out-Null
          }

          $VmPath  = $root                              # Path de la VM → raíz del disco
          $VhdPath = Join-Path $vhdRoot "$VmName.vhdx"  # D:\VMNAME\Virtual Hard Disks\VMNAME.vhdx

          Write-Host "Path base Hyper-V       : $VmPath"
          Write-Host "Carpeta discos (vhdRoot): $vhdRoot"
          Write-Host "Disco VHDX              : $VhdPath"

          # 3. Validar acceso a la ISO en la NAS (usa SMB Global Mapping)
          $effectiveIsoPath = $null
          if ($IsoPath -and $IsoPath.Trim() -ne '') {
            if (-not (Test-Path $IsoPath)) {
              throw "La ISO no es accesible desde este host: $IsoPath"
            }
            $effectiveIsoPath = $IsoPath
            Write-Host "ISO remota a usar (NAS): $effectiveIsoPath"
          }

          # 4. Crear VHDX si no existe
          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
          }

          # 5. Crear VM si no existe
          if (-not (Get-VM -Name $VmName -ErrorAction SilentlyContinue)) {
            New-VM -Name $VmName `
                   -MemoryStartupBytes $MemoryBytes `
                   -Generation 2 `
                   -VHDPath $VhdPath `
                   -SwitchName $SwitchName `
                   -Path $VmPath | Out-Null
          } else {
            Write-Host "La VM $VmName ya existe, no se crea de nuevo."
          }

          # 6. CPU y memoria dinámica
          Set-VMProcessor -VMName $VmName -Count $CpuCount
          Set-VMMemory -VMName $VmName `
            -DynamicMemoryEnabled $true `
            -MinimumBytes 1GB `
            -MaximumBytes ($MemoryBytes * 2)

          # 7. Montar ISO remota en DVD (sin copiar, usando UNC directo)
          if ($effectiveIsoPath) {
            Write-Host "Montando ISO remota en la VM: $effectiveIsoPath"

            $dvd = Get-VMDvdDrive -VMName $VmName -ErrorAction SilentlyContinue
            if ($dvd) {
              Set-VMDvdDrive -VMName $VmName `
                -ControllerNumber $dvd.ControllerNumber `
                -ControllerLocation $dvd.ControllerLocation `
                -Path $effectiveIsoPath
            } else {
              Add-VMDvdDrive -VMName $VmName -Path $effectiveIsoPath | Out-Null
            }

            $dvd = Get-VMDvdDrive -VMName $VmName
            Set-VMFirmware -VMName $VmName -FirstBootDevice $dvd
          } else {
            Write-Host "ADVERTENCIA: no se montó ISO (ruta no válida)."
          }

          # 8. Iniciar VM
          try {
            Start-VM -Name $VmName -ErrorAction SilentlyContinue
          } catch {
            Write-Host "ADVERTENCIA: no se pudo iniciar la VM $VmName : $($_.Exception.Message)"
          }

        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          CandidateDrives: "{{ candidate_drives }}"
      delegate_to: "{{ hyperv_host }}"
      run_once: true
