- name: Validar acceso al ISO desde Hyper-V
  hosts: SMXHVCEDIS
  gather_facts: no
  collections:
    - ansible.windows

  vars:
    iso_path: "\\\\SMXFILES\\isos\\SERVER_EVAL_x64FRE_es-es.iso"

  tasks:
    - name: Test-Path desde Hyper-V
      ansible.windows.win_powershell:
        script: |
          param([string]$IsoPath)
          whoami
          try {
            $ok = Test-Path $IsoPath -ErrorAction Stop
            Write-Host "Test-Path: $ok"
          } catch {
            Write-Host "ERROR: $($_.Exception.Message)"
          }
        parameters:
          IsoPath: "{{ iso_path }}"
