---
- name: Prueba sencilla en servidores
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Mostrar mensaje de prueba
      ansible.builtin.debug:
        msg: "¡Conexión exitosa con Ansible!"
