---
- name: Crear VM Rocky Linux 9.6 en Hyper-V (ISO Rocky + Kickstart OEMDRV)
  hosts: "{{ hyperv_host }}"
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts Hyper-V permitidos
    hyperv_hosts:
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXFCHVB
      - SMXHYPVA

    # vSwitch por defecto
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar discos de la VM
    candidate_drives:
      - 'D'
      - 'E'

    # ISO Rocky por defecto en NAS
    iso_path_default: '\\10.138.120.130\isos\Rocky-9.6-x86_64-dvd.iso'

    # NAS para el SMB Global Mapping
    nas_server: '10.138.120.130'
    nas_share: 'isos'
    nas_user: 'NASUSER_AQUI'
    nas_pass: 'NASPASS_AQUI'

    # Ruta local de oscdimg.exe
    oscdimg_path: 'C:\\Oscdimg\\oscdimg.exe'

    # Instalación Rocky Linux
    root_password: "Passw0rd."
    linux_user: "adm"
    linux_password: "Passw0rd."
    timezone: "America/Mexico_City"
    lang: "es_MX.UTF-8"

  tasks:
    # -------------------------------------------------------------------
    # 0) Validaciones
    # -------------------------------------------------------------------
    - name: Validar host Hyper-V permitido
      ansible.builtin.assert:
        that:
          - inventory_hostname in hyperv_hosts
        fail_msg: "El host {{ inventory_hostname }} no está permitido."

    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
          - vm_ip is defined
          - vm_mask is defined
          - vm_gateway is defined
          - vm_dns1 is defined
        fail_msg: "Faltan variables obligatorias."

    - name: Normalizar variables
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"
        vm_dns2_eff: "{{ vm_dns2 | default(vm_dns1) }}"
        ks_dir: "C:\\kickstart\\{{ vm_name }}"
        ks_cfg_path: "C:\\kickstart\\{{ vm_name }}\\ks.cfg"
        ks_iso_path: "C:\\ISOs\\{{ vm_name }}_ks.iso"

    # -------------------------------------------------------------------
    # 1) SMB Global Mapping hacia la NAS
    # -------------------------------------------------------------------
    - name: Crear SMB Global Mapping hacia la NAS para Hyper-V
      ansible.windows.win_shell: |
        $Server = "{{ nas_server }}"
        $Share  = "{{ nas_share }}"
        $User   = "{{ nas_user }}"
        $Pass   = "{{ nas_pass }}"

        $remotePath = "\\$Server\$Share"
        Write-Host "Intentando mapear $remotePath con $User"

        $sec  = ConvertTo-SecureString $Pass -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential($User, $sec)

        if (Get-Command -Name New-SmbGlobalMapping -ErrorAction SilentlyContinue) {
            $existing = Get-SmbGlobalMapping -RemotePath $remotePath -ErrorAction SilentlyContinue
            if (-not $existing) {
                try { net use $remotePath /delete /y | Out-Null } catch { }
                New-SmbGlobalMapping -RemotePath $remotePath -Credential $cred -Persistent $true -ErrorAction Stop
            }
            Write-Host "MAPPING-OK: $remotePath"
        }
        else {
            Write-Host "NEW-SMBGLOBALMAPPING NO DISPONIBLE: usando net use"
            net use $remotePath /user:$User $Pass /persistent:no
            Write-Host "NETUSE-OK: $remotePath"
        }
      register: smb_map_result

    - name: Mostrar salida del SMB Mapping
      ansible.builtin.debug:
        var: smb_map_result.stdout

    # -------------------------------------------------------------------
    # 2) Preparar carpetas e inyectar Kickstart
    # -------------------------------------------------------------------
    - name: Crear carpeta local para ISOs
      ansible.windows.win_file:
        path: "C:\\ISOs"
        state: directory

    - name: Crear carpeta Kickstart para la VM
      ansible.windows.win_file:
        path: "{{ ks_dir }}"
        state: directory

    - name: Generar archivo ks.cfg para Kickstart
      ansible.builtin.template:
        src: "templates/ks.cfg.j2"
        dest: "{{ ks_cfg_path }}"

    # -------------------------------------------------------------------
    # 3) Crear ISO OEMDRV con Kickstart usando oscdimg
    # ------------------------------------------------------------
