---
- name: Crear VM Rocky Linux 9.6 en Hyper-V (ISO Rocky + Kickstart OEMDRV)
  hosts: "{{ hyperv_host }}"
  gather_facts: no

  collections:
    - ansible.windows

  vars:
    # Hosts Hyper-V permitidos
    hyperv_hosts:
      - SMXHVCEDIS
      - SMXHVFCAWS19
      - SMXHVFCBWS19
      - SMXFCHVB
      - SMXHYPVA

    # vSwitch por defecto
    default_switch: 'LAN-Prod'

    # Unidades donde se pueden guardar discos de la VM
    candidate_drives:
      - 'D'
      - 'E'

    # ISO Rocky por defecto en NAS
    iso_path_default: '\\10.138.120.130\isos\Rocky-9.6-x86_64-dvd.iso'

    # NAS para el SMB Global Mapping
    nas_server: '10.138.120.130'
    nas_share: 'isos'
    nas_user: 'NASUSER_AQUI'
    nas_pass: 'NASPASS_AQUI'

    # Ruta local de oscdimg.exe
    oscdimg_path: 'C:\\Oscdimg\\oscdimg.exe'

    # Instalación Rocky Linux
    root_password: "Passw0rd."
    linux_user: "adm"
    linux_password: "Passw0rd."
    timezone: "America/Mexico_City"
    lang: "es_MX.UTF-8"

  tasks:
    # -------------------------------------------------------------------
    # 0) Validaciones
    # -------------------------------------------------------------------
    - name: Validar host Hyper-V permitido
      ansible.builtin.assert:
        that:
          - inventory_hostname in hyperv_hosts
        fail_msg: "El host {{ inventory_hostname }} no está permitido."

    - name: Validar variables obligatorias
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - memory_gb is defined
          - cpu is defined
          - disk_gb is defined
          - vm_ip is defined
          - vm_mask is defined
          - vm_gateway is defined
          - vm_dns1 is defined
        fail_msg: "Faltan variables obligatorias."

    - name: Normalizar variables
      ansible.builtin.set_fact:
        v_switch_eff: "{{ v_switch | default(default_switch) }}"
        iso_path_eff: "{{ iso_path | default(iso_path_default) }}"
        memory_bytes: "{{ (memory_gb | int) * 1073741824 }}"
        disk_bytes: "{{ (disk_gb | int) * 1073741824 }}"
        cpu_count: "{{ cpu | int }}"
        vm_dns2_eff: "{{ vm_dns2 | default(vm_dns1) }}"
        ks_dir: "C:\\kickstart\\{{ vm_name }}"
        ks_cfg_path: "C:\\kickstart\\{{ vm_name }}\\ks.cfg"
        ks_iso_path: "C:\\ISOs\\{{ vm_name }}_ks.iso"

    # -------------------------------------------------------------------
    # 1) SMB Global Mapping hacia la NAS
    # -------------------------------------------------------------------
    - name: Crear SMB Global Mapping hacia la NAS para Hyper-V
      ansible.windows.win_shell: |
        $Server = "{{ nas_server }}"
        $Share  = "{{ nas_share }}"
        $User   = "{{ nas_user }}"
        $Pass   = "{{ nas_pass }}"

        $remotePath = "\\$Server\$Share"
        Write-Host "Intentando mapear $remotePath con $User"

        $sec  = ConvertTo-SecureString $Pass -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential($User, $sec)

        if (Get-Command -Name New-SmbGlobalMapping -ErrorAction SilentlyContinue) {
            $existing = Get-SmbGlobalMapping -RemotePath $remotePath -ErrorAction SilentlyContinue
            if (-not $existing) {
                try { net use $remotePath /delete /y | Out-Null } catch { }
                New-SmbGlobalMapping -RemotePath $remotePath -Credential $cred -Persistent $true -ErrorAction Stop
            }
            Write-Host "MAPPING-OK: $remotePath"
        }
        else {
            Write-Host "NEW-SMBGLOBALMAPPING NO DISPONIBLE: usando net use"
            net use $remotePath /user:$User $Pass /persistent:no
            Write-Host "NETUSE-OK: $remotePath"
        }
      register: smb_map_result

    - name: Mostrar salida del SMB Mapping
      ansible.builtin.debug:
        var: smb_map_result.stdout

    # -------------------------------------------------------------------
    # 2) Preparar carpetas e inyectar Kickstart
    # -------------------------------------------------------------------
    - name: Crear carpeta local para ISOs
      ansible.windows.win_file:
        path: "C:\\ISOs"
        state: directory

    - name: Crear carpeta Kickstart para la VM
      ansible.windows.win_file:
        path: "{{ ks_dir }}"
        state: directory

    - name: Generar archivo ks.cfg para Kickstart
      ansible.builtin.template:
        src: "templates/ks.cfg.j2"
        dest: "{{ ks_cfg_path }}"

    # -------------------------------------------------------------------
    # 3) Crear ISO OEMDRV con Kickstart usando oscdimg
    # -------------------------------------------------------------------
    - name: Crear ISO Kickstart (OEMDRV)
      ansible.windows.win_powershell:
        script: |
          param($SourcePath, $IsoPath, $OscdimgPath)

          if (-not (Test-Path $SourcePath)) { throw "No existe carpeta Kickstart: $SourcePath" }
          if (-not (Test-Path $OscdimgPath)) { throw "No existe oscdimg: $OscdimgPath" }

          if (Test-Path $IsoPath) { Remove-Item -Path $IsoPath -Force }

          $args = @('-lOEMDRV','-n','-m',$SourcePath,$IsoPath)

          $p = Start-Process -FilePath $OscdimgPath -ArgumentList $args -Wait -PassThru -NoNewWindow
          if ($p.ExitCode -ne 0) { throw "oscdimg falló con código $($p.ExitCode)" }

          Write-Host "ISO creada: $IsoPath"
        parameters:
          SourcePath: "{{ ks_dir }}"
          IsoPath: "{{ ks_iso_path }}"
          OscdimgPath: "{{ oscdimg_path }}"

    # -------------------------------------------------------------------
    # 4) Crear VM, adjuntar ISOs y configurar firmware
    # -------------------------------------------------------------------
    - name: Crear VM Rocky Linux 9.6 en Hyper-V
      ansible.windows.win_powershell:
        script: |
          param($VmName,$MemoryBytes,$DiskBytes,$CpuCount,$SwitchName,$IsoPath,$KsIsoPath,$CandidateDrives,$VlanId)

          Import-Module Hyper-V

          # Seleccionar unidad con más espacio
          $drives = foreach ($d in $CandidateDrives) {
            try { Get-PSDrive -Name $d -ErrorAction Stop } catch { $null }
          }

          $bestDrive = $drives | Sort-Object Free -Descending | Select-Object -First 1
          $root = $bestDrive.Root
          $clusterRoot = "$root\$VmName"
          $vhdRoot = Join-Path $clusterRoot "Virtual Hard Disks"

          New-Item -ItemType Directory -Path $clusterRoot -Force | Out-Null
          New-Item -ItemType Directory -Path $vhdRoot -Force | Out-Null

          $VhdPath = Join-Path $vhdRoot "$VmName.vhdx"

          if (-not (Test-Path $VhdPath)) {
            New-VHD -Path $VhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
          }

          $vm = Get-VM -Name $VmName -ErrorAction SilentlyContinue
          if (-not $vm) {
            New-VM -Name $VmName -MemoryStartupBytes $MemoryBytes -Generation 2 -SwitchName $SwitchName -Path $root -NoVHD | Out-Null
          }

          # Insertar discos
          Add-VMHardDiskDrive -VMName $VmName -ControllerNumber 0 -ControllerLocation 2 -Path $VhdPath -ErrorAction SilentlyContinue

          # Insertar DVD Rocky y OEMDRV
          Get-VMDvdDrive -VMName $VmName | Remove-VMDvdDrive -VMName $VmName -Confirm:$false -ErrorAction SilentlyContinue

          Add-VMDvdDrive -VMName $VmName -ControllerNumber 0 -ControllerLocation 0 -Path $IsoPath
          Add-VMDvdDrive -VMName $VmName -ControllerNumber 0 -ControllerLocation 1 -Path $KsIsoPath

          # Secure Boot OFF, boot desde DVD
          $dvd = Get-VMDvdDrive -VMName $VmName | Where-Object { $_.Path -eq $IsoPath }
          Set-VMFirmware -VMName $VmName -EnableSecureBoot Off -FirstBootDevice $dvd

          Start-VM -Name $VmName
        parameters:
          VmName: "{{ vm_name }}"
          MemoryBytes: "{{ memory_bytes }}"
          DiskBytes: "{{ disk_bytes }}"
          CpuCount: "{{ cpu_count }}"
          SwitchName: "{{ v_switch_eff }}"
          IsoPath: "{{ iso_path_eff }}"
          KsIsoPath: "{{ ks_iso_path }}"
          CandidateDrives: "{{ candidate_drives }}"
          VlanId: "{{ vm_vlan | default('0') | int }}"
