---
- name: Instalar agente con usuario dedicado (solo instalador)
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Usar Python moderno del host (evita errores con Ansible 2.18+)
    ansible_python_interpreter: /usr/bin/python3

    # ====== Parámetros del instalador ======
    # Descarga directa del script (sin clonar repo)
    installer_raw_url: "https://raw.githubusercontent.com/acuetosantillana/Playbooks/main/Instaladores/installScript.sh"
    install_script_abs: "/home/admendpoint/installScript.sh"
    install_args: "install"

  pre_tasks:
    - name: Bootstrap mínimo - asegurar sudo (vía CLI; sin módulos yum/dnf)
      ansible.builtin.shell: |
        set -o pipefail
        command -v sudo >/dev/null 2>&1 || {
          if command -v yum >/dev/null 2>&1; then
            yum -y install sudo
          else
            dnf -y install sudo
          fi
        }
      args:
        executable: /bin/bash
      changed_when: false
      when: ansible_os_family in ["RedHat","Rocky","AlmaLinux","CentOS"]

  tasks:
    - name: Crear usuario admendpoint con home y shell
      ansible.builtin.user:
        name: admendpoint
        shell: /bin/bash
        create_home: yes
        home: /home/admendpoint

    - name: Asegurar permisos y propiedad del home
      ansible.builtin.file:
        path: /home/admendpoint
        owner: admendpoint
        group: admendpoint
        mode: "0750"
        state: directory

    - name: Descargar SOLO el instalador desde GitHub (sin clonar repo)
      ansible.builtin.get_url:
        url: "{{ installer_raw_url }}"
        dest: "{{ install_script_abs }}"
        owner: admendpoint
        group: admendpoint
        mode: "0750"
        force: yes
        validate_certs: yes

    - name: Publicar sudoers para admendpoint con comandos NOPASSWD
      ansible.builtin.copy:
        dest: /etc/sudoers.d/admendpoint
        mode: "0440"
        owner: root
        group: root
        content: |
          # Permisos específicos para el usuario admendpoint
          Defaults:admendpoint !requiretty
          admendpoint     ALL=(root)      NOPASSWD: \
            /home/admendpoint/installScript.sh, \
            /usr/bin/vi /etc/systemd/system/cpla.service, \
            /usr/bin/systemctl start cpla.service, \
            /usr/bin/systemctl stop cpla.service, \
            /usr/bin/systemctl status cpla.service, \
            /usr/bin/systemctl restart cpla.service, \
            /usr/bin/systemctl daemon-reload, \
            /usr/bin/sh -x /home/admendpoint/installScript.sh install
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ejecutar instalador vía sudo como admendpoint (requiere NOPASSWD)
      become: false
      become_user: admendpoint
      args:
        chdir: "{{ (install_script_abs | dirname) }}"
      ansible.builtin.shell: |
        sudo -n /usr/bin/sh -x "{{ install_script_abs }}" {{ install_args }}
