---
- name: Instalar agente con usuario dedicado
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Usar Python moderno del host (evita el error de future annotations)
    ansible_python_interpreter: /usr/bin/python3

    # ==== Parámetros de tu repo e instalador ====
    repo_url: "https://github.com/acuetosantillana/Playbooks.git"
    repo_version: "main"
    repo_dest: "/home/admendpoint/agent"
    script_src_in_repo: "Instaladores/installScript.sh"
    install_script_abs: "/home/admendpoint/installScript.sh"
    install_args: "install"

  pre_tasks:
    - name: Bootstrap de git/sudo usando CLI (yum si existe, si no dnf)
      ansible.builtin.shell: |
        set -o pipefail
        PKGS=""
        command -v git  >/dev/null 2>&1 || PKGS="$PKGS git"
        command -v sudo >/dev/null 2>&1 || PKGS="$PKGS sudo"
        if [ -n "$PKGS" ]; then
          if command -v yum >/dev/null 2>&1; then
            yum -y install $PKGS
          else
            dnf -y install $PKGS
          fi
        fi
      args:
        executable: /bin/bash
      changed_when: false
      when: ansible_os_family in ["RedHat","Rocky","AlmaLinux","CentOS"]

  tasks:
    - name: Crear usuario admendpoint con home y shell
      ansible.builtin.user:
        name: admendpoint
        shell: /bin/bash
        create_home: yes
        home: /home/admendpoint

    - name: Asegurar permisos y propiedad del home
      ansible.builtin.file:
        path: /home/admendpoint
        owner: admendpoint
        group: admendpoint
        mode: "0750"
        state: directory

    - name: Clonar/actualizar repositorio del instalador (como admendpoint)
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_version }}"
        update: yes
      become_user: admendpoint

    - name: Copiar/actualizar script de instalación a ubicación fija en $HOME (desde remoto)
      ansible.builtin.copy:
        src: "{{ repo_dest }}/{{ script_src_in_repo }}"
        dest: "{{ install_script_abs }}"
        owner: admendpoint
        group: admendpoint
        mode: "0750"
        remote_src: true

    # (Alternativa si prefieres symlink en lugar de copia)
    # - name: Enlazar script del repo a la ruta fija en $HOME
    #   ansible.builtin.file:
    #     src: "{{ repo_dest }}/{{ script_src_in_repo }}"
    #     dest: "{{ install_script_abs }}"
    #     state: link
    #     owner: admendpoint
    #     group: admendpoint

    - name: Publicar sudoers para admendpoint con comandos NOPASSWD
      ansible.builtin.copy:
        dest: /etc/sudoers.d/admendpoint
        mode: "0440"
        owner: root
        group: root
        content: |
          # Permisos específicos para el usuario admendpoint
          Defaults:admendpoint !requiretty
          admendpoint     ALL=(root)      NOPASSWD: \
            /home/admendpoint/installScript.sh, \
            /usr/bin/vi /etc/systemd/system/cpla.service, \
            /usr/bin/systemctl start cpla.service, \
            /usr/bin/systemctl stop cpla.service, \
            /usr/bin/systemctl status cpla.service, \
            /usr/bin/systemctl restart cpla.service, \
            /usr/bin/systemctl daemon-reload, \
            /usr/bin/sh -x /home/admendpoint/installScript.sh install
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ejecutar instalador como usuario admendpoint
      become_user: admendpoint
      args:
        chdir: "{{ (install_script_abs | dirname) }}"
      ansible.builtin.shell: |
        /bin/sh -x "{{ install_script_abs }}" {{ install_args }}
