---
- name: Instalar Zabbix Agent 2 en Linux - Santillana
  hosts: linux
  become: yes
  gather_facts: yes
  serial: 10

  vars:
    zabbix_server_ip: "10.138.120.3"
    zabbix_version: "7.4"

  tasks:

    - name: Detectar version de OS
      set_fact:
        os_major: "{{ ansible_distribution_major_version }}"

    - name: Verificar si zabbix-agent2 ya esta instalado
      shell: rpm -q zabbix-agent2
      register: agent_installed
      ignore_errors: yes
      changed_when: false

    - name: Eliminar repo Zabbix anterior
      shell: rpm -e zabbix-release
      ignore_errors: yes
      when: agent_installed.rc != 0

    - name: Instalar repositorio Zabbix correcto para EL{{ os_major }}
      shell: >
        rpm -Uvh https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/rocky/{{ os_major }}/noarch/zabbix-release-latest-{{ zabbix_version }}.el{{ os_major }}.noarch.rpm
      when: agent_installed.rc != 0
      register: repo_install
      ignore_errors: yes

    - name: Limpiar cache DNF
      shell: dnf clean all -y
      when: agent_installed.rc != 0

    - name: Instalar zabbix-agent2
      dnf:
        name: zabbix-agent2
        state: present

    - name: Configurar Server
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Server="
        line: "Server={{ zabbix_server_ip }}"

    - name: Configurar ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^ServerActive="
        line: "ServerActive={{ zabbix_server_ip }}"

    - name: Configurar Hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Hostname="
        line: "Hostname={{ inventory_hostname }}"

    - name: Agregar HostMetadata
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^HostMetadata="
        line: "HostMetadata=linux"
        insertafter: EOF

    - name: Abrir puerto 10050 en firewall
      firewalld:
        port: 10050/tcp
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes

    - name: Habilitar e iniciar zabbix-agent2
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: started

    - name: Verificar estado del agente
      shell: systemctl is-active zabbix-agent2
      register: agent_status
      changed_when: false

    - name: Resultado
      debug:
        msg: "{{ inventory_hostname }} ({{ ansible_host }}) | OS: Rocky Linux {{ os_major }} | Agente: {{ agent_status.stdout }}"